# -*- coding: utf-8 -*-
"""LVMH Stock & Financial Data Collection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ef30M39wh-HIHtfJtScSKhPY-Wq8JO3i

# Data Collection

## Stock Data

### Stock Data 2019 to 2022
"""

# Install libraries (only needed once per Colab session)
!pip install yfinance pandas numpy tabula-py matplotlib seaborn

# Import libraries
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tabula
from google.colab import files
import os

# Create the directory structure if it doesn't exist
os.makedirs("PTC_Phase1/Data_Collection/stock_data", exist_ok=True)

# Step 1: Download stock prices for LVMH, Kering, and CAC 40 (for Beta calculation)
tickers = ["MC.PA", "KER.PA", "^FCHI"]
stock_data = yf.download(tickers, start="2019-01-01", end="2022-12-31")["Close"]

# Calculate daily returns and drop NA values
returns = stock_data.pct_change().dropna()

# Step 2: Calculate Beta for LVMH and Kering relative to CAC 40
covariance_lvmh = np.cov(returns["MC.PA"], returns["^FCHI"])[0, 1]
variance_cac40 = np.var(returns["^FCHI"])
beta_lvmh = covariance_lvmh / variance_cac40

covariance_kering = np.cov(returns["KER.PA"], returns["^FCHI"])[0, 1]
beta_kering = covariance_kering / variance_cac40

# Step 3: Fetch additional financial metrics for LVMH and Kering
lvmh = yf.Ticker("MC.PA")
kering = yf.Ticker("KER.PA")

# Fetch P/E ratio, EV/EBITDA, and other metrics
lvmh_pe = lvmh.info.get("trailingPE", "N/A")
lvmh_ev_ebitda = lvmh.info.get("enterpriseToEbitda", "N/A")
lvmh_market_cap = lvmh.info.get("marketCap", "N/A")

kering_pe = kering.info.get("trailingPE", "N/A")
kering_ev_ebitda = kering.info.get("enterpriseToEbitda", "N/A")
kering_market_cap = kering.info.get("marketCap", "N/A")

# Step 4: Create a DataFrame to store the metrics
metrics = pd.DataFrame({
    "Metric": ["Beta", "P/E Ratio", "EV/EBITDA", "Market Cap (EUR)"],
    "LVMH": [beta_lvmh, lvmh_pe, lvmh_ev_ebitda, lvmh_market_cap],
    "Kering": [beta_kering, kering_pe, kering_ev_ebitda, kering_market_cap]
})

# Step 5: Save the stock returns and metrics to CSV in the specified directory
returns_file_path = "PTC_Phase1/Data_Collection/stock_data/stock_returns_2019_2022.csv"
metrics_file_path = "PTC_Phase1/Data_Collection/stock_data/stock_metrics_2019_2022.csv"

returns.to_csv(returns_file_path)
metrics.to_csv(metrics_file_path)

# Optional: Preview the data
print("Stock Returns:")
print(returns.head())

print("\nStock Metrics:")
print(metrics)

"""### Oil & FX"""

import os
import yfinance as yf

#  Create the folder
os.makedirs("PTC_Phase1/Data_Collection/stock_data", exist_ok=True)

#  Download the data
oil_fx_data = yf.download(["BZ=F", "EURUSD=X"], start="2019-01-01", end="2022-12-31")["Close"]

# Save the file
oil_fx_data.to_csv("PTC_Phase1/Data_Collection/stock_data/oil_fx_2019_2022.csv")

# Check if it worked
print("File saved successfully!")
print(os.listdir("PTC_Phase1/Data_Collection/stock_data"))  # This will show you the files in the folder

"""## Macro Data

### Retail Sales: EU
"""

!mkdir -p "Data_Collection/Macro_Data/Retail_Sales:_EU"
from google.colab import files
uploaded = files.upload()  # Upload retail_sales_eu.csv
!mv retail_sales_us.csv "Data_Collection/Macro_Data/Retail_Sales:_EU/"

"""### Retail Sales: US"""

!mkdir -p "Data_Collection/Macro_Data/Retail_Sales:_US"
from google.colab import files
uploaded = files.upload()  # Upload retail_sales_us.csv
!mv retail_sales_us.csv "Data_Collection/Macro_Data/Retail_Sales:_US/"

"""### Geopolitical Timeline"""

import pandas as pd

# Create the folder structure
!mkdir -p "Data_Collection/Macro_Data/Geopolitical_Timeline"

# Upload the file from your desktop to Colab
from google.colab import files
uploaded = files.upload()

# Load the CSV file, using the first row as header and parsing 'Date'
events = pd.read_csv("geopolitical_events_2019_2022.csv", dayfirst=True, parse_dates=['Date'])

# Display the column names and first few rows
print("Column names:", events.columns)
print("\nFirst few rows:")
print(events.head())

# Strip any extra spaces from column names
events.columns = events.columns.str.strip()

# Drop unnecessary columns (like the empty ones represented by 'Unnamed')
events = events.drop(columns=[col for col in events.columns if 'Unnamed' in col])

# Display the cleaned column names
print("\nCleaned column names:", events.columns)

# Display the first few rows to verify
print("\nFirst few rows after parsing dates and cleaning:")
print(events.head())

# Move the file to the correct folder
!mv "geopolitical_events_2019_2022.csv" "Data_Collection/Macro_Data/Geopolitical_Timeline/"

# Verify the file is in the correct location
import os
print("\nFiles in Geopolitical_Timeline folder:")
print(os.listdir("Data_Collection/Macro_Data/Geopolitical_Timeline"))

"""## Financial Metrics"""

# Create the Financial_Data folder if it doesn't exist
!mkdir -p Financial_Data

# Upload the Financials.csv file
from google.colab import files
uploaded = files.upload()

# Move the uploaded Financials.csv file to the Financial_Data folder
!mv Financials.csv Financial_Data/

import pandas as pd

# Load the CSV file
financials_df = pd.read_csv("Financial_Data/Financials.csv")

# Display the first few rows of the data
print(financials_df.head())

"""## Merged Data

### ALL
"""

import pandas as pd
import numpy as np
import os

# Create the folder structure if it doesn't exist
os.makedirs("Data_Collection/Merged_Data", exist_ok=True)

# Use the already loaded financials_df as the financial_metrics
financial_metrics = financials_df.copy()

# Use the 'returns' DataFrame already loaded in a previous cell
stock_returns_df = returns.copy()

# Use the 'events' DataFrame already loaded in a previous cell
geopolitical_events_df = events.copy()

# Drop rows with NaN in 'Date' from geopolitical_events_df to prevent KeyError: 'nan'
geopolitical_events_df = geopolitical_events_df.dropna(subset=['Date'])

# Load oil and FX data
oil_fx_2019_2022_df = pd.read_csv("PTC_Phase1/Data_Collection/stock_data/oil_fx_2019_2022.csv", index_col=0, parse_dates=True)

# Drop rows where 'Year' is NaN before converting to int
financial_metrics = financial_metrics.dropna(subset=['Year'])

# Convert 'Year' to 'Date' in financial_metrics
financial_metrics['Date'] = pd.to_datetime(financial_metrics['Year'].astype(int), format='%Y')

# Function to align financial metrics with the nearest trading day
def align_financial_metrics_with_trading_days(financial_metrics, stock_returns):
    aligned_data = []

    for _, row in financial_metrics.iterrows():
        year = row['Date'].year
        # Find the nearest trading day in the stock returns data
        trading_days_in_year = stock_returns.loc[str(year)].index
        if not trading_days_in_year.empty:
            # Find the nearest trading day to the start of the year
            nearest_trading_day = min(trading_days_in_year, key=lambda x: abs(x - row['Date']))
            aligned_row = row.to_dict()
            aligned_row['Date'] = nearest_trading_day
            aligned_data.append(aligned_row)

    return pd.DataFrame(aligned_data)

# Align financial metrics with the nearest trading day
aligned_financial_metrics = align_financial_metrics_with_trading_days(financial_metrics, stock_returns_df)

# Calculate Beta for each company
def calculate_beta(stock_returns, market_returns):
    covariance = np.cov(stock_returns, market_returns)[0, 1]
    variance = np.var(market_returns)
    return covariance / variance

# Assuming CAC 40 (^FCHI) is used as the market index
market_returns = stock_returns_df['^FCHI'].dropna()
lvmh_returns = stock_returns_df['MC.PA'].dropna()
kering_returns = stock_returns_df['KER.PA'].dropna()

beta_lvmh = calculate_beta(lvmh_returns, market_returns)
beta_kering = calculate_beta(kering_returns, market_returns)

# Add Beta to the aligned financial metrics
aligned_financial_metrics.loc[aligned_financial_metrics['Company'] == 'LVMH', 'Beta'] = beta_lvmh
aligned_financial_metrics.loc[aligned_financial_metrics['Company'] == 'Kering', 'Beta'] = beta_kering

# Merge aligned financial metrics with stock returns
merged_data = pd.merge(aligned_financial_metrics, stock_returns_df, left_on='Date', right_index=True, how='left')

# Align geopolitical events with the nearest trading day in financial metrics
def align_geopolitical_events_with_trading_days(geopolitical_events, stock_returns):
    aligned_events = []

    for _, row in geopolitical_events.iterrows():
        event_date = row['Date']
        # Explicitly check for NaT and skip if found
        if pd.isna(event_date):
            continue

        year = event_date.year
        # Find the nearest trading day in the stock returns data
        # We can directly use stock_returns.index to check for year presence
        # and then filter, but for precise nearest day, iterating through the year's index is better.
        # Ensure the year is in the index of stock_returns_df
        year_str = str(year)
        if year_str in stock_returns.index.year.astype(str).unique(): # Check if the year exists in stock_returns
            trading_days_in_year = stock_returns.loc[year_str].index
            if not trading_days_in_year.empty:
                # Find the nearest trading day to the event date
                nearest_trading_day = min(trading_days_in_year, key=lambda x: abs(x - event_date))
                aligned_row = row.to_dict()
                aligned_row['Date'] = nearest_trading_day
                aligned_events.append(aligned_row)

    return pd.DataFrame(aligned_events)

# Align geopolitical events with the nearest trading day
aligned_geopolitical_events = align_geopolitical_events_with_trading_days(geopolitical_events_df, stock_returns_df)

# Merge with aligned geopolitical events
merged_data = pd.merge(merged_data, aligned_geopolitical_events, on='Date', how='left', suffixes=('', '_event'))

# Merge with oil and FX data
merged_data = pd.merge(merged_data, oil_fx_2019_2022_df, left_on='Date', right_index=True, how='left')

# Save the merged dataset
merged_file_path = "Data_Collection/Merged_Data/aligned_merged_data_2019_2022.csv"
merged_data.to_csv(merged_file_path, index=False)

# Display the first few rows of the merged data
print(merged_data.head())

"""### Stock Performance Over Time"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load stock returns data
stock_returns = pd.read_csv("PTC_Phase1/Data_Collection/stock_data/stock_returns_2019_2022.csv", index_col=0, parse_dates=True)

# Resample to monthly returns
monthly_returns = stock_returns.resample('ME').mean()

# Plot monthly returns with consistent colors
plt.figure(figsize=(14, 7))
sns.lineplot(data=monthly_returns['MC.PA'], label='LVMH', color='blue')
sns.lineplot(data=monthly_returns['KER.PA'], label='Kering', color='orange', linestyle='--')
plt.title("Monthly Stock Returns for LVMH and Kering (2019-2022)")
plt.xlabel("Date")
plt.ylabel("Monthly Return (%)")
plt.legend(title="Company")
plt.grid(True)
plt.show()

"""### Financial Metrics Analysis"""

# Load financial metrics data
financial_metrics = pd.read_csv("PTC_Phase1/Data_Collection/stock_data/stock_metrics_2019_2022.csv")

# Plot revenue growth
plt.figure(figsize=(12, 6))
sns.barplot(data=financial_metrics, x='Metric', y='LVMH', hue='Metric') # Updated for the 'metrics' DataFrame structure
plt.title("Financial Metrics for LVMH (2019-2022)")
plt.xlabel("Metric")
plt.ylabel("Value")
plt.xticks(rotation=45, ha='right')
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 6))
sns.barplot(data=financial_metrics, x='Metric', y='Kering', hue='Metric') # Updated for the 'metrics' DataFrame structure
plt.title("Financial Metrics for Kering (2019-2022)")
plt.xlabel("Metric")
plt.ylabel("Value")
plt.xticks(rotation=45, ha='right')
plt.grid(True)
plt.tight_layout()
plt.show()

"""### Geopolitical Event Impact"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load geopolitical events data from the correct path
geopolitical_events = pd.read_csv("Data_Collection/Macro_Data/Geopolitical_Timeline/geopolitical_events_2019_2022.csv", parse_dates=['Date'], dayfirst=True)

# Drop rows where 'Date' is NaT before plotting
geopolitical_events = geopolitical_events.dropna(subset=['Date'])

# Ensure stock_data is available (it's loaded in a previous cell t5FpOKei6cPV)

plt.figure(figsize=(16, 9)) # Increased figure size for better readability
ax = sns.lineplot(x=stock_data.index, y=stock_data['MC.PA'], label='LVMH Stock Price', color='blue', linewidth=1.5)

# Set aesthetic improvements
plt.title("LVMH Stock Price with Geopolitical Events (2019-2022)", fontsize=16, fontweight='bold')
plt.xlabel("Date", fontsize=12)
plt.ylabel("Stock Price (EUR)", fontsize=12)
plt.legend(title="Company", loc='upper left', fontsize=10, title_fontsize=12, frameon=True, shadow=True)
plt.grid(True, linestyle='--', alpha=0.7)
plt.xticks(rotation=45, ha='right')

# Get current y-axis limits to place annotations below the plot area
min_y, max_y = ax.get_ylim()

# Define a window to check for stock downturn/upturn after an event (e.g., 5 trading days)
downturn_window_days = 5
downturn_threshold_percent = -0.02 # e.g., a 2% drop is considered a downturn
upturn_threshold_percent = 0.02 # e.g., a 2% rise is considered an upturn

# Iterate through events for annotations and downturn analysis
# Sort events by date to potentially help with annotation placement, though true non-overlap requires more complex logic
geopolitical_events = geopolitical_events.sort_values(by='Date').reset_index(drop=True)

# Determine a base y-position for annotations, and then stagger them
base_annotation_y = min_y - (max_y - min_y) * 0.20 # Place annotations 20% of the y-range below min_y
annotation_y_step = (max_y - min_y) * 0.03 # Small step to stagger text

for i, event in geopolitical_events.iterrows():
    event_date = event['Date']
    event_label = event['Event']

    # Find the nearest trading day for the event and price on that day
    if event_date in stock_data.index:
        price_on_event = stock_data.loc[event_date, 'MC.PA']
        event_trading_day_idx = stock_data.index.get_loc(event_date)
    else:
        # If event_date is not a trading day, find the closest previous trading day
        nearest_trading_days = stock_data.index[stock_data.index <= event_date]
        if not nearest_trading_days.empty:
            event_date = nearest_trading_days[-1] # Use the closest previous trading day
            price_on_event = stock_data.loc[event_date, 'MC.PA']
            event_trading_day_idx = stock_data.index.get_loc(event_date)
        else:
            continue # Skip event if no suitable trading day found

    # Find the stock price after the downturn_window_days (trading days)
    price_after_event = None
    price_change_percent = 0
    if event_trading_day_idx + downturn_window_days < len(stock_data):
        price_after_event = stock_data['MC.PA'].iloc[event_trading_day_idx + downturn_window_days]
        price_change_percent = (price_after_event - price_on_event) / price_on_event

    # Determine annotation color and text based on downturn/upturn
    line_color = 'gray' # Default color
    arrow_color = 'gray'
    annotation_suffix = ''

    if price_change_percent < downturn_threshold_percent:
        line_color = 'red'
        arrow_color = 'red'
        annotation_suffix = f" (↓ {price_change_percent:.1%})"
    elif price_change_percent > upturn_threshold_percent:
        line_color = 'green'
        arrow_color = 'green'
        annotation_suffix = f" (↑ {price_change_percent:.1%})"

    # Draw the vertical line for the event
    ax.axvline(x=event_date, color=line_color, linestyle='--', alpha=0.7, lw=1)

    # Add text annotation using annotate, staggered for better readability
    text_y_pos = base_annotation_y + (i % 3) * annotation_y_step # Stagger annotations vertically

    ax.annotate(event_label + annotation_suffix,
                xy=(event_date, price_on_event), # Pointing to the event on the stock price line
                xytext=(event_date, text_y_pos), # Place text below the plot area
                textcoords='data',
                arrowprops=dict(arrowstyle="->", color=arrow_color, shrinkA=5, shrinkB=5, lw=0.8),
                ha='center', # Horizontal alignment for text
                rotation=45, # Rotate text to prevent overlap
                fontsize=9,
                color='black', # Text color can be black for readability against white box
                bbox=dict(boxstyle="round,pad=0.3", fc="white", ec=arrow_color, lw=0.5, alpha=0.9))

# Adjust the y-axis limits to accommodate the annotations below
ax.set_ylim(bottom=base_annotation_y - annotation_y_step * 2) # Extend y-axis further down

plt.tight_layout() # Adjust layout to prevent labels/annotations from being cut off
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load geopolitical events data from the correct path
geopolitical_events_kering = pd.read_csv("Data_Collection/Macro_Data/Geopolitical_Timeline/geopolitical_events_2019_2022.csv", parse_dates=['Date'], dayfirst=True)

# Drop rows where 'Date' is NaT before plotting
geopolitical_events_kering = geopolitical_events_kering.dropna(subset=['Date'])

# Ensure stock_data is available (it's loaded in a previous cell t5FpOKei6cPV)

plt.figure(figsize=(16, 9)) # Increased figure size for better readability
ax = sns.lineplot(x=stock_data.index, y=stock_data['KER.PA'], label='Kering Stock Price', color='red', linewidth=1.5)

# Set aesthetic improvements
plt.title("Kering Stock Price with Geopolitical Events (2019-2022)", fontsize=16, fontweight='bold')
plt.xlabel("Date", fontsize=12)
plt.ylabel("Stock Price (EUR)", fontsize=12)
plt.legend(title="Company", loc='upper left', fontsize=10, title_fontsize=12, frameon=True, shadow=True)
plt.grid(True, linestyle='--', alpha=0.7)
plt.xticks(rotation=45, ha='right')

# Get current y-axis limits to place annotations below the plot area
min_y, max_y = ax.get_ylim()

# Define a window to check for stock downturn/upturn after an event (e.g., 5 trading days)
downturn_window_days = 5
downturn_threshold_percent = -0.02 # e.g., a 2% drop is considered a downturn
upturn_threshold_percent = 0.02 # e.g., a 2% rise is considered an upturn

# Iterate through events for annotations and downturn analysis
# Sort events by date to potentially help with annotation placement, though true non-overlap requires more complex logic
geopolitical_events_kering = geopolitical_events_kering.sort_values(by='Date').reset_index(drop=True)

# Determine a base y-position for annotations, and then stagger them
base_annotation_y = min_y - (max_y - min_y) * 0.20 # Place annotations 20% of the y-range below min_y
annotation_y_step = (max_y - min_y) * 0.03 # Small step to stagger text

for i, event in geopolitical_events_kering.iterrows():
    event_date = event['Date']
    event_label = event['Event']

    # Find the nearest trading day for the event and price on that day
    if event_date in stock_data.index:
        price_on_event = stock_data.loc[event_date, 'KER.PA']
        event_trading_day_idx = stock_data.index.get_loc(event_date)
    else:
        # If event_date is not a trading day, find the closest previous trading day
        nearest_trading_days = stock_data.index[stock_data.index <= event_date]
        if not nearest_trading_days.empty:
            event_date = nearest_trading_days[-1] # Use the closest previous trading day
            price_on_event = stock_data.loc[event_date, 'KER.PA']
            event_trading_day_idx = stock_data.index.get_loc(event_date)
        else:
            continue # Skip event if no suitable trading day found

    # Find the stock price after the downturn_window_days (trading days)
    price_after_event = None
    price_change_percent = 0
    if event_trading_day_idx + downturn_window_days < len(stock_data):
        price_after_event = stock_data['KER.PA'].iloc[event_trading_day_idx + downturn_window_days]
        price_change_percent = (price_after_event - price_on_event) / price_on_event

    # Determine annotation color and text based on downturn/upturn
    line_color = 'gray' # Default color
    arrow_color = 'gray'
    annotation_suffix = ''

    if price_change_percent < downturn_threshold_percent:
        line_color = 'red'
        arrow_color = 'red'
        annotation_suffix = f" (↓ {price_change_percent:.1%})"
    elif price_change_percent > upturn_threshold_percent:
        line_color = 'green'
        arrow_color = 'green'
        annotation_suffix = f" (↑ {price_change_percent:.1%})"

    # Draw the vertical line for the event
    ax.axvline(x=event_date, color=line_color, linestyle='--', alpha=0.7, lw=1)

    # Add text annotation using annotate, staggered for better readability
    text_y_pos = base_annotation_y + (i % 3) * annotation_y_step # Stagger annotations vertically

    ax.annotate(event_label + annotation_suffix,
                xy=(event_date, price_on_event), # Pointing to the event on the stock price line
                xytext=(event_date, text_y_pos), # Place text below the plot area
                textcoords='data',
                arrowprops=dict(arrowstyle="->", color=arrow_color, shrinkA=5, shrinkB=5, lw=0.8),
                ha='center', # Horizontal alignment for text
                rotation=45, # Rotate text to prevent overlap
                fontsize=9,
                color='black', # Text color can be black for readability against white box
                bbox=dict(boxstyle="round,pad=0.3", fc="white", ec=arrow_color, lw=0.5, alpha=0.9))

# Adjust the y-axis limits to accommodate the annotations below
ax.set_ylim(bottom=base_annotation_y - annotation_y_step * 2) # Extend y-axis further down

plt.tight_layout() # Adjust layout to prevent labels/annotations from being cut off
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load geopolitical events data from the correct path
geopolitical_events = pd.read_csv("Data_Collection/Macro_Data/Geopolitical_Timeline/geopolitical_events_2019_2022.csv", parse_dates=['Date'], dayfirst=True)

# Drop rows where 'Date' is NaT before plotting and sort events
geopolitical_events = geopolitical_events.dropna(subset=['Date'])
geopolitical_events = geopolitical_events.sort_values(by='Date').reset_index(drop=True)

plt.figure(figsize=(18, 10)) # Even larger figure for more space
ax = sns.lineplot(x=stock_data.index, y=stock_data['MC.PA'], label='LVMH Stock Price', color='blue', linewidth=1.5)
sns.lineplot(x=stock_data.index, y=stock_data['KER.PA'], label='Kering Stock Price', color='red', linewidth=1.5, ax=ax)

# Set aesthetic improvements
plt.title("LVMH and Kering Stock Prices with Geopolitical Events and Energy Shocks (2019-2022)", fontsize=18, fontweight='bold')
plt.xlabel("Date", fontsize=14)
plt.ylabel("Stock Price (EUR)", fontsize=14)
plt.legend(title="Company", loc='upper left', fontsize=12, title_fontsize=14, frameon=True, shadow=True)
plt.grid(True, linestyle='--', alpha=0.7)
plt.xticks(rotation=45, ha='right', fontsize=10)
plt.yticks(fontsize=10)

# Get current y-axis limits to place annotations below the plot area
min_y, max_y = ax.get_ylim()

# Define a window to check for stock downturn/upturn after an event (e.g., 5 trading days)
downturn_window_days = 5
downturn_threshold_percent = -0.02 # e.g., a 2% drop is considered a downturn
upturn_threshold_percent = 0.02 # e.g., a 2% rise is considered an upturn

# Determine a base y-position for annotations, pushed further down
base_annotation_y = min_y - (max_y - min_y) * 0.40 # Increased multiplier for more space below
annotation_y_step = (max_y - min_y) * 0.04 # Increased step to stagger text more effectively

for i, event in geopolitical_events.iterrows():
    event_date = event['Date']
    event_label = event['Event']

    # Find the nearest trading day for the event and prices on that day
    if event_date in stock_data.index:
        price_on_event_lvmh = stock_data.loc[event_date, 'MC.PA']
        price_on_event_kering = stock_data.loc[event_date, 'KER.PA']
        event_trading_day_idx = stock_data.index.get_loc(event_date)
    else:
        nearest_trading_days = stock_data.index[stock_data.index <= event_date]
        if not nearest_trading_days.empty:
            event_date = nearest_trading_days[-1]
            price_on_event_lvmh = stock_data.loc[event_date, 'MC.PA']
            price_on_event_kering = stock_data.loc[event_date, 'KER.PA']
            event_trading_day_idx = stock_data.index.get_loc(event_date)
        else:
            continue # Skip event if no suitable trading day found

    price_change_percent_lvmh = 0
    price_change_percent_kering = 0
    if event_trading_day_idx + downturn_window_days < len(stock_data):
        price_after_event_lvmh = stock_data['MC.PA'].iloc[event_trading_day_idx + downturn_window_days]
        price_change_percent_lvmh = (price_after_event_lvmh - price_on_event_lvmh) / price_on_event_lvmh

        price_after_event_kering = stock_data['KER.PA'].iloc[event_trading_day_idx + downturn_window_days]
        price_change_percent_kering = (price_after_event_kering - price_on_event_kering) / price_on_event_kering

    # Determine annotation text and color based on combined LVMH and Kering impact
    line_color = 'gray' # Default color
    arrow_color = 'gray'
    annotation_suffix = ''

    lvmh_impact_str = ''
    if price_change_percent_lvmh < downturn_threshold_percent:
        lvmh_impact_str = f"LVMH ↓ {price_change_percent_lvmh:.1%}"
    elif price_change_percent_lvmh > upturn_threshold_percent:
        lvmh_impact_str = f"LVMH ↑ {price_change_percent_lvmh:.1%}"

    kering_impact_str = ''
    if price_change_percent_kering < downturn_threshold_percent:
        kering_impact_str = f"Kering ↓ {price_change_percent_kering:.1%}"
    elif price_change_percent_kering > upturn_threshold_percent:
        kering_impact_str = f"Kering ↑ {price_change_percent_kering:.1%}"

    # Set line and arrow color based on impact: red if any significant drop, green if any significant rise (and no drops), else gray
    if price_change_percent_lvmh < downturn_threshold_percent or price_change_percent_kering < downturn_threshold_percent:
        line_color = 'red'
        arrow_color = 'red'
    elif price_change_percent_lvmh > upturn_threshold_percent or price_change_percent_kering > upturn_threshold_percent:
        line_color = 'green'
        arrow_color = 'green'

    # Combine impact strings, handling cases where only one has significant impact
    if lvmh_impact_str and kering_impact_str:
        annotation_suffix = f" ({lvmh_impact_str}, {kering_impact_str})"
    elif lvmh_impact_str:
        annotation_suffix = f" ({lvmh_impact_str})"
    elif kering_impact_str:
        annotation_suffix = f" ({kering_impact_str})"

    # Draw the vertical line for the event
    ax.axvline(x=event_date, color=line_color, linestyle='--', alpha=0.7, lw=1)

    # Use a fixed y-position below the x-axis for text, staggered
    text_y_pos = base_annotation_y + (i % 4) * annotation_y_step # Stagger more for potentially longer text

    # Point to LVMH's price for the arrow origin (arbitrary choice if both are plotted)
    arrow_origin_price = price_on_event_lvmh

    ax.annotate(event_label + annotation_suffix,
                xy=(event_date, arrow_origin_price), # Pointing to the event on LVMH stock price line
                xycoords='data',
                xytext=(event_date, text_y_pos),    # Place text below the plot area
                textcoords='data',
                arrowprops=dict(arrowstyle="->", color=arrow_color, shrinkA=5, shrinkB=5, lw=0.8),
                ha='center',
                rotation=45,
                fontsize=9,
                color='black',
                bbox=dict(boxstyle="round,pad=0.3", fc="white", ec=arrow_color, lw=0.5, alpha=0.9))

# Adjust the y-axis limits to accommodate the annotations below
ax.set_ylim(bottom=base_annotation_y - annotation_y_step * 2)

plt.tight_layout() # Adjust layout to prevent labels/annotations from being cut off
plt.show()

"""### Tracking Oil and EUR/US"""

# Load oil and FX data
oil_fx_data = pd.read_csv("PTC_Phase1/Data_Collection/stock_data/oil_fx_2019_2022.csv", index_col=0, parse_dates=True)

# Plot oil prices with stock prices
plt.figure(figsize=(14, 7))
ax1 = sns.lineplot(x=stock_data.index, y=stock_data['MC.PA'], label='LVMH Stock Price', color='blue')
ax2 = ax1.twinx()
sns.lineplot(x=oil_fx_data.index, y=oil_fx_data['BZ=F'], label='Brent Crude Price', color='orange', ax=ax2)
plt.title("LVMH Stock Price vs Brent Crude Price (2019-2022)")
ax1.set_xlabel("Date")
ax1.set_ylabel("Stock Price")
ax2.set_ylabel("Brent Crude Price")
ax1.legend(loc='upper left')
ax2.legend(loc='upper right')
plt.grid(True)
plt.show()
